= 深入理解spring data JPA-Specifications 和 Querydsl
xiaoqu <xiaoqu>
3.0, July 29, 2022: AsciiDoc article template
:toc:
:icons: font
在我之前的博客里， 介绍了Spring Data JPA的基本特性。 在这篇文章中我会深入的讲解一些特性，关于他们怎样可以简化你的数据层实现 Spring Data Repository 抽象了一系列的接口， 基于编程模型，一些工厂类，和一个spring的命名空间帮助你去简单的配置基础设施。 一个常见的repo 接口是这样的：
[source, java]
----
public interface CustomerRepository extends JpaRepository<Customer, Long> {

  Customer findByEmailAddress(String emailAddress); // <1>

  List<Customer> findByLastname(String lastname, Sort sort); // <2>

  Page<Customer> findByFirstname(String firstname, Pageable pageable); // <3>
}
----
<1> 表示通过email地址获取customer
<2> 表示通过lastName 获取所有的customer， 通过 `sort`进行排序。
<3> 返回分页的customers

尽管这种途径非常容易和方便（你甚至可以不写一行实现代码，去实现查询）。
他有两个缺点：1，查询方法的数量会增长的很快对于一个大型的应用程序来说。2，这些查询方法定义了一个固定的
标准。 怎样去避免两个缺点，去动态的构建查询语句？

如果你用了很长时间的JPA， 你可能会想到： 这不是就是 `Criteria API` 适用的场景吗?
没问题, 接下来使用 `Criteria Api`验证一下我们的业务需求。使用场景：老顾客生日的时候给他们发一个贺卡。 我们如何处理呢？

我们可能会拆成两部分： 那些被我们称作老顾客用户的生日。 让我们假设老顾客的用户在两年前已经创建好了，下边是我们用`JPA 2.0 Criteria API`的实现方式。

[source,java]
----
LocalDate today = new LocalDate();

CriteriaBuilder builder = em.getCriteriaBuilder();
CriteriaQuery<Customer> query = builder.createQuery(Customer.class);
Root<Customer> root = query.from(Customer.class);

Predicate hasBirthday = builder.equal(root.get(Customer_.birthday), today);
Predicate isLongTermCustomer = builder.lessThan(root.get(Customer_.createdAt), today.minusYears(2);
query.where(builder.and(hasBirthday, isLongTermCustomer));
em.createQuery(query.select(root)).getResultList();
----

我们new了一个 `LocalDate` 为了方便，接下来的三行模版代码是创建JPA必备的实例，接下来的两行是构建查询语句，第一行是构建了实际执行sql的predicate. 我们使用jpa 2.0引入的原始类，并且通过注解处理api 生成。这里最大的问题就是： 代码不外部化(externalize)和不可重用，因为你需要构建一个： `CriteriaBuilder`, `CriteriaQuery` 和 `Root`， 并且代码可读性会很差，很难通过第一眼去快速推断出代码的意图。

==  Specifications

为了能够定义可重用的`Predicate`s, 我们引入了`Specification` 接口， 它来源于Eric Evan\'s的《领域驱动设计》, 定义一个 specification作为一个表达式，我们的`Specification`定义一个entity。 这实际上是一连串的单方法。
[source,java]
----
public interface Specification<T> {
  Predicate toPredicate(Root<T> root, CriteriaQuery query, CriteriaBuilder cb);
}
----
接下来我们可以简单的通过helper class。
[source,java]
----
public CustomerSpecifications {

  public static Specification<Customer> customerHasBirthday() {
    return new Specification<Customer> {
      public Predicate toPredicate(Root<T> root, CriteriaQuery query, CriteriaBuilder cb) {
        return cb.equal(root.get(Customer_.birthday), today);
      }
    };
  }

  public static Specification<Customer> isLongTermCustomer() {
    return new Specification<Customer> {
      public Predicate toPredicate(Root<T> root, CriteriaQuery query, CriteriaBuilder cb) {
        return cb.lessThan(root.get(Customer_.createdAt), new LocalDate.minusYears(2));
      }
    };
  }
}
----
不可否认的是， 这并不是最优雅的代码，但是这能够快速和漂亮的实现我们最初的需求：我们可以推出一连串的specification, 那么接下来的问题就是： 我们怎么执行这些`specification`？
为了做到这些， 你简答的**extend** `JpaSpecificationExecutor`在我们的`Repository`接口，因此你需要在你的repository接口做些更改，例如下面：
[source,java]
----
public interface CustomerRepository extends JpaRepository<Customer>, JpaSpecificationExecutor {
  // Your query methods here
}
----
然后调用方就可以这么用：
[source,java]
----
customerRepository.findAll(hasBirthday());
customerRepository.findAll(isLongTermCustomer());
----
基本的repository实现将会准`CriteriaQuery`, `Root`,和 `CriteriaBuilder` 并且执行查询。
但是我们不是简单的创建个查询方法不久获得了我们需要的功能了吗？对的， 但是别忘了我们的第二部分初始化的需求： 我们想通过自由的创建`Specification`去组合我们需要的功能，为了能够做到这些，我们创建了`Specification`的工具类，提供`and(...)` 和 `or(...)`方法去方便的聚合`Specification` 当然了为了让代码更加的可读性，我们也提供了`where(...)`的语法糖。
[source,java]
----
customerRepository.findAll(where(customerHasBirthday()).and(isLongTermCustomer()));
----
这种代码读起来很流畅，提成了可读性，也提供了额外的灵活性比起单独的使用JPA Criteria Api。但是这种写法会有一个问题： 就是会有一些编码上的effort。

== Querydsl

为了避免上边的问题， 开源项目 http://www.querydsl.com/[Querydsl]通过另一种方式实现了。
就像Jpa那样使用Java6的注解处理器去生成类，并且生成了很多方便的API。 这个项目另一个酷的地方及时：不仅仅支持JPA，而且还支持：Hibernate， JDO， Lucene， JDBC，甚至原始的集合。

为了能够setup Querydsl， 添加下面东西到pom.xml里。
[source,xml]
----
<plugin>
  <groupId>com.mysema.maven</groupId>
  <artifactId>maven-apt-plugin</artifactId>
  <version>1.0</version>
  <executions>
    <execution>
      <phase>generate-sources</phase>
      <goals>
        <goal>process</goal>
      </goals>
      <configuration>
        <outputDirectory>target/generated-sources</outputDirectory>
        <processor>com.mysema.query.apt.jpa.JPAAnnotationProcessor</processor>
      </configuration>
    </execution>
  </executions>
</plugin>
----
在我们的代码库里会生成查询类`QCustomer`， 和`Customer`在同一个包里。

[source,java]
----
QCustomer customer = QCustomer.customer;
LocalDate today = new LocalDate();
BooleanExpression customerHasBirthday = customer.birthday.eq(today);
BooleanExpression isLongTermCustomer = customer.createdAt.lt(today.minusYears(2));
----
这不仅仅是流畅的英语，`BooleanExpression`s 可用性很高。这个能够让我们远离`Specification`包装器，
另外在你写代码的时候IDE也会有智能提示。

为了执行Querydsl的语句， 你需要你的repo extend ` QueryDslPredicateExecutor:`
[source,java]
----
public interface CustomerRepository extends JpaRepository<Customer>, QueryDslPredicateExecutor {
  // Your query methods here
}
----

然后可以这么使用：
[source ,java]
----
BooleanExpression customerHasBirthday = customer.birthday.eq(today);
BooleanExpression isLongTermCustomer = customer.createdAt.lt(today.minusYears(2));
customerRepository.findAll(customerHasBirthday.and(isLongTermCustomer));
----
== 总结
JPA repo的抽象允许我们执行表达式通过JPA的Criteria api，或者通过`Specification`包装的Criteria。
或者通过Querydsl的表达式。