== 角色改变对我的影响2

最近体会了半个月的TL（铺路侠）， 有了一些新的思考的对比。

=== 差别一

忙着解决团队里的各种问题。

. 团队里某个成员，站会更新卡的时候没进度。这个时候站会结束我需要找对应的人去了解一下原因。
. 团队成员被某个东西block了。 我需要了解原因，帮助他们尝试去解决问题，以及提供相关的思路。
. 团队里的新人，要时时刻刻去关注。比如他是否知道主动寻求帮助。
. 卡是否够接下来的开发，是否出现开发空转的情况
. 团队速率如何，迭代的卡是否做得完，是否需要团队加班, 以及原因分析。
. 团队氛围怎么样， 团队目前的状况是否健康呀。
. 给团队传达一些指令。
...

总之你要维护这个团队，把团队当亲生儿子小心呵护着。

=== 差别二

每天忙着各种会。

. 和客户约的会。
. 客户和我约的会。
. 内部align的会。
. 跨团队沟通的会。

=== 差别三

工作重心的改变。

. 每天工作的重心，从代码移到了团队。

=== 差别四

个人的转变。

. 重心从个人成长，变成了如何带领整个团队成长。 之后才变成了个人成长。

=== [.line-through]#TL# *铺路侠* 的一天

8:00起床 -> 8:20洗漱完毕，下楼吃饭 -> 8:40吃毕，出门去公司 -> 8:55到公司 ->

9:00 看一下团队的进度，卡墙上的卡状态, 捋一下今天的事情 -> 9:30 团队开始站会 -> 9:45 站会结束 ->

10:00 解决完毕团队站会中上述的种种问题 -> 10:00和其他team的TL沟通，推动新的实践落地 ->  10：30 和BA聊下个迭代的技术方案，以及写卡方式。 ->

11:10 解决团队成员临时暴露出的问题 -> 11:30 下楼吃饭 ->

12:00 吃饭完毕，回到公司. -> 12:30 项目治理的会 ->

13:30 开会结束，开始下午的工作。 ->

2:00 在全项目上推广新技术，收集反馈。 -> 2:45 团队人员能力建设培养计划会 ->

4:30 开会途中，需要解决团队成员的紧急问题, 开会找人，分析问题 ->

5:00 看一眼BA上午写的卡，有些问题。沟通解决 -> 5:30 开始团队的code review ->

6:30 code review 准时结束。 -> 终于有自己的的时间啦。。。