= Java 并发常见问题

== Thread Run和Thread Start 有什么区别
Main difference is that when program calls start() method a new Thread is created and code inside run() method is executed in new Thread while if you call run() method directly no new Thread is created and code inside run() will execute on current Thread

=== 证明

https://github.com/xiaoquisme/java-learning/blob/master/src/main/java/com/example/ThreadRunDiffStart.java

== Future和FutureTask的区别

1. Future is a base interface and defines the abstraction of an object which promises results to be available in the future while FutureTask is an implementation of the Future interface.

2. Future is a parametric interface and type-safe written as Future<V>, where V denotes value.

3. Future provides get() method to get a result, which is blocking method and blocks until the result is available to Future.

4. Future interface also defines cancel() method to cancel the task.

5. isDone() and isCancelled() method is used to query Future task states. isDone() returns true if the task is completed and the result is available to Future. If you call the get() method, after isDone() returned true then it should return immediately. On the other hand, isCancelled() method returns true, if this task is canceled before its completion.


6. Future has four sub-interfaces, each with additional functionality e.g. Response, RunnableFuture, RunnableScheduledFuture, and ScheduledFuture. RunnableFuture also implements Runnable and successful finish of run() method cause completion of this Future.


7. FutureTask and SwingWorker are two well-known implementations of the Future interface. FutureTask also implements RunnableFuture interface, which means this can be used as Runnable and can be submitted to ExecutorService for execution.


8. Though most of the time ExecutorService creates FutureTask for you, i.e. when you submit() Callable or Runnable object. You can also create it manually.


9. FutureTask is normally used to wrap Runnable or Callable objects and submit them to ExecutorService for asynchronous execution.