


= OR-3850 从BLM导入经销商合作商
曲廉卿 <lqqu@thoughtworks.com>
4.0, Aug 13 , 2022
:toc:
:icons: font


== 工序
[example]
测试不在工序范围内，只需
fellow现有的代码仓库的规则，唯一要求测试覆盖率不低于80%。

=== 工序-bff
. 修改接口 XXX 和文档保持一致
. 修改service XXX， CRUD/ 一些功能
. 修改client xxx, CRUD 一些request/response/url

=== 工序- service

. 修改mq consumer xxx的topic为xxx，修改message,实现功能xxx。
. 修改controller xxx的方法xxx， 和bff的请求保持一致。
. 修改service xxx的方法xxx， 组合：client/repo/mq/configuration 实现功能xxx
. 修改repo xxx的方法xxx，entity/查询方法，实现功能xxx
. 添加flyway xxx CUD table xxx， 实现功能xxx
. 修改client xxx 的方法xxx 实现功能xxx。
. 修改ConfigurationProperties对应的class xxx， 添加配置项，实现功能xxx。
. 修改mapper XXX的方法 XXX， 实现xxx功能。
. 修改mq xxx的topic xxx， 修改publish message xxx，实现功能xxx

== story


=== AC1:

经销商合作商来源是BLM，并且全网通用
Given 在电池去向页面
When 选择经销商合作商
Then 可以看到来自BLM的经销商合作商

=== example

当获取电池合作商的时候,应该返回 厂商 + 经销商的全量数据.

=== 工序-bff(website-bff)
. 工序1： 修改接口 `/api/sales-website/battery-whereabouts/partner` 的request和response和文档保持一致
. 工序2： 修改 service `BlmService` 的 `getOrganizationsByPartnerType` 方法，删除 `partnerType` 参数
. 工序3：修改client  `BlmClient` 的 `getOrganizationsByPartnerType` 方法，删除`@RequestParam(name = "partnerType"`

=== 工序-service(blm-integration)
. 工序2：修改controller `BatteryWhereaboutsController` 的方法 `getOrganizationsByWhereType`,重命名为：`getOrganizationsByPartnerType`, 删除参数：`@RequestParam(name = "partnerType"`
. 工序3：修改service `PartnerService`的方法`getOemAndDealerPartner`，实现功能： 返回所有的经销商合作商（OEM+dealer）
. 工序3：修改service `PartnerService`删除方法`getOemPartner`和`getPartnersByPartnerTypeAndDealerId`.
. 工序4：修改repo`PartnerRepository` 删除方法`findAllByPartnerTypeAndDealerIdAndDeletedIsFalse`
. 工序4： 修改repo`PartnerRepository`的方法:`findAllByDealerIdInAndDeletedIsFalse`,重命名为：`findAllByDeletedIsFalse`.

=== AC2:

经销商不可添加/编辑经销商合作商
Given 在电池去向页面
When 选择经销商合作商
Then 不可以填写经销商合作商
When 选择其中一个经销商合作商
Then 不可以编辑合作商信息

=== example:

当保存电池去向的时候,quest 的 partenrInfo.id不为空,且在系统中能找到, 返回200

=== 工序-bff(website-bff)
. 工序1： 修改接口 `/api/sales-website/battery-whereabouts/upsert` 删除 `UpdateBatteryWhereaboutsRequest` 中的对象 `partnerInfo`
. 工序1： 修改接口 `/api/sales-website/battery-whereabouts/upsert` 参数`UpdateBatteryWhereaboutsRequest`新增字段 `organizationId`
. 工序1： 修改接口 `/api/sales-website/battery-whereabouts/upsert` 为@PutMapping
. 工序1： 修改接口 `/api/sales-website/battery-whereabouts/upsert` url为 `/api/sales-website/battery-whereabouts`
. 工序1： 修改接口 `/api/sales-website/battery-whereabouts` 必填字段的校验和文档一致
. 工序1： 修改接口 `BlmController#updateOrInsertBatteryWhereabouts` 重命名 方法名为 `updateBatteryWhereabouts`
. 工序2： 修改service `blmService.updateOrInsertBatteryWhereabouts` 重命名为 `blmService.updateBatteryWhereabouts`

=== 工序-service(blm-integration)
. 工序2：修改controller `BatteryWhereaboutsController`的方法`updateBatteryWhereabouts` 为@PutMapping
. 工序2：修改controller `BatteryWhereaboutsController`的方法`updateBatteryWhereabouts`，删除参数`request` 中的对象 `partnerInfo`
. 工序2：修改controller `BatteryWhereaboutsController`的方法`updateBatteryWhereabouts`，在参数 `request` 中新增字段 `organizationId`
. 工序3：修改service `BatteryWhereaboutsService`删除方法`updateBatteryWhereabouts`中的 `request.getPartnerInfo()`
. 工序3：修改service `BatteryWhereaboutsService`删除方法`updateBatteryWhereabouts`中的 `PARTNER_MAPPER.toPartnerMatchingCommand`
. 工序3：修改service `BatteryWhereaboutsService`删除方法`updateBatteryWhereabouts`中的 `partnerService.matchOrCreatePartner`
. 工序3：修改service `BatteryWhereaboutsService`将方法`doUpdate`中的代码移动至 `updateBatteryWhereabouts`方法中，并删除`doUpdate`方法
. 工序3：修改service `BatteryWhereaboutsProviderImpl`的方法`submitBatteryWhereabouts`中的`validator.validate(blmBatteryWhereaboutsDto)`校验规则和文档一致
. 工序4：修改entity `BatteryWhereabouts` 新增字段`organizationId`


=== AC3

经销商保存电池去向的时候,如果 parenerInfo.id 为空, 提示: partenerInfo.id不能为空.

=== example

当保存电池去向的时候,quest 的 partenrInfo.id为空,返回 400, partenerInfo.id不能为空.


=== 工序-service(blm-integration)
. 工序2：修改controller `BatteryWhereaboutsController`的方法`updateBatteryWhereabouts`，参数 `request` 中的`organizationId`字段上加注解@NotBlank(message = "organization id is mandatory")


=== AC4

经销商保存电池去向的时候,如果 parenerInfo.id 不合法的id, 提示: invalid organization.

=== example

经销商保存电池去向的时候,如果 parenerInfo.id 不合法的id,返回 400, 提示：invalid organization.

=== 工序-service(blm-integration)

. 工序3：修改service 在 `BatteryWhereaboutsService`的方法`updateBatteryWhereabouts` 中新增查询partnerRepository.findByOrganizationUniqueId(request.getOrganizationId())
. 工序3：修改service 在 `BatteryWhereaboutsService`的方法`updateBatteryWhereabouts` 中新增校验：若上一步查到的数据为null，则 throw new BadRequestException("invalid organization");

=== AC5

当同步合作厂商的时候，应该同步经销商和厂商的的所有数据。

example：当定时任务调用接口：/battery-whereabouts/partners/synchronize时，应该从blm同步过来经销商和厂商合作电池厂家的数据。

NOTE: 注意 fellow现有的同步规则

=== 工序-service

. 工序3 修改service *PartnerService* 的方法 *syncBlmPartners*
. 工序4 修改repo *PartnerRepository* 的方法 *findAllByPartnerType* 为 *findAll* 实现功能： 能够查询所有电池去向合作商（厂商/经销商）
. 工序8 修改mapper *PartnerMapper* 的 *toPartner* 方法， 实现 *partnerType* 能够根据dealer和OEM正确的mapping。
. 工序6 修改client *BlmClient* 的方法 *queryAllOrganizations* 的response添加字段和契约文档保持一致
