= 服务拆分与重构
曲 廉卿 <qulianqing1314@qq.com>
1.0, May 23, 2022: init
:toc:
:icons: font
:url-quickref: https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/

== 内容简介
主要聊一些微服务拆分的自己在项目上的实践总结，以及个人对服务拆分和重构的关系

== 背景
主要介绍一下《project》 record和inspection的关系，已经record服务的历史遗留问题（比如《project》+起的迅速，服务被其他供应商糟蹋）


== 方案
. 数据库不变，新增从库，
. 原数据库新增用户(添加相关表的权限，旧的用户移除相关的权限)
. 路由切换
. 从库变主库
. 删除无用的其他表
. 经过两个release（牵扯功能存在问题，和删除代码 的安全起见）

== 总结

TODO://三种境界展开聊一下

. 迁移代码的三重境界
.. 无脑的copy, paste，代码搬运工
.. 修复存在的问题（如：URL设计不合理，接口设计不合理，系统的各种考核指标达标，重构系统中坏味道严重的代码）
.. 修复业务逻辑中存在的不合理的地方，或者修复一个隐藏的bug
. 删除代码（特别重要）
.. 讲一下service-bff的遗留问题


== 与重构的关系

.重构定义
[quote,Martin Fowler,《重构》]
____
所谓重构（refactoring） 是这样一个过程： 在不改变代码外在行为的前提下，对代码作出修改，以改进程序的内部结构。
____


服务拆分，它改变了代码的外部行为。 和明显打破了重构定义的前提。

那么是不是可以对服务拆分这么定义：

.服务拆分定义
[quote, ]
____
所谓 *服务拆分* 是这样一个过程： 在不改变 *系统* 外在行为的前提下，对 *系统* 作出修改， 以改进 *产品* 的内部结构
____

TIP: 粗体是和重构定义的差别


《重构》第二版刚出的时候， 我就立马买了。当时正在正在重构一个有着 *10* 年生命的系统代码，被重构代码折磨的死去活来。拿到了健总的十六字心法，如获至宝，才将我的那次大规模重构顺利的完成。

那么服务拆分和《重构》第二版里 `译者序`里提到的健总的十六字心法有没有关系呢？
我想应该是有的：

.十六字心法定义:
[quote, 王健]
____
旧的不变,

新的创建,

一键替换,

旧的再见。
____


.我所理解的关系
[source,text]
----
旧的不变,<1>

新的创建,<2>

一键替换,<3>

旧的再见。<4>
----
<1> 旧的服务对外暴露的接口不变
<2> 新的服务接口创建
<3> 旧服务的接口一键切为新服务的接口
<4> 旧的服务接口删除
